on: workflow_call

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Hello world
        run: echo "Hello world from ${{ matrix.os }}"